insert into Cities (CityName) values ('Yuanqian');
insert into Cities (CityName) values ('Périgueux');
insert into Cities (CityName) values ('Igbo Ora');
insert into Cities (CityName) values ('Tianzhou');
insert into Cities (CityName) values ('Jarinu');
insert into Cities (CityName) values ('Noebana');
insert into Cities (CityName) values ('Blendis');
insert into Cities (CityName) values ('Krasnokholm');
insert into Cities (CityName) values ('Caronoan West');
insert into Cities (CityName) values ('Kangar');
insert into Cities (CityName) values ('Krasnogvardeyets');
insert into Cities (CityName) values ('Medaya');
insert into Cities (CityName) values ('Lebao');
insert into Cities (CityName) values ('Saint-Priest-en-Jarez');
insert into Cities (CityName) values ('Västerås');
insert into Cities (CityName) values ('Imbituva');
insert into Cities (CityName) values ('San Juan Bautista');
insert into Cities (CityName) values ('Fukadale');
insert into Cities (CityName) values ('Jingxin');
insert into Cities (CityName) values ('Sirindhorn');
insert into Cities (CityName) values ('Mytishchi');
insert into Cities (CityName) values ('Pappádos');
insert into Cities (CityName) values ('Palebunan');
insert into Cities (CityName) values ('Monticello');
insert into Cities (CityName) values ('Zaplavnoye');
insert into Cities (CityName) values ('Kamiennik');
insert into Cities (CityName) values ('Qianzhou');
insert into Cities (CityName) values ('Kamensk-Ural’skiy');
insert into Cities (CityName) values ('Pinghu');
insert into Cities (CityName) values ('Villarrica');
insert into Cities (CityName) values ('Kolkhozobod');
insert into Cities (CityName) values ('Palmira');
insert into Cities (CityName) values ('Sere');
insert into Cities (CityName) values ('Novi Šeher');
insert into Cities (CityName) values ('San Miguel');
insert into Cities (CityName) values ('Waiwukak');
insert into Cities (CityName) values ('Bailiang');
insert into Cities (CityName) values ('Hal’shany');
insert into Cities (CityName) values ('Nagbacalan');
insert into Cities (CityName) values ('Vilyuchinsk');
insert into Cities (CityName) values ('As Sawdā');
insert into Cities (CityName) values ('Iwye');
insert into Cities (CityName) values ('Regulice');
insert into Cities (CityName) values ('Tampa');
insert into Cities (CityName) values ('Dongshan');
insert into Cities (CityName) values ('Trần Văn Thời');
insert into Cities (CityName) values ('Galátsi');
insert into Cities (CityName) values ('Santana do Paraíso');
insert into Cities (CityName) values ('Ożarów');
insert into Cities (CityName) values ('Tô Hạp');
insert into Cities (CityName) values ('Gendiwu');
insert into Cities (CityName) values ('Ossora');
insert into Cities (CityName) values ('Xiaojiangba');
insert into Cities (CityName) values ('Buenavista');
insert into Cities (CityName) values ('Aubergenville');
insert into Cities (CityName) values ('Xintang');
insert into Cities (CityName) values ('Stavropol’');
insert into Cities (CityName) values ('Kembang');
insert into Cities (CityName) values ('Cagwait');
insert into Cities (CityName) values ('Irákleia');
insert into Cities (CityName) values ('Velikiy Novgorod');
insert into Cities (CityName) values ('Geldrop');
insert into Cities (CityName) values ('Fuli');
insert into Cities (CityName) values ('Gävle');
insert into Cities (CityName) values ('La Huaca');
insert into Cities (CityName) values ('Haymā’');
insert into Cities (CityName) values ('Huayuan');
insert into Cities (CityName) values ('Cruzeiro');
insert into Cities (CityName) values ('Paris 08');
insert into Cities (CityName) values ('Hässelby');
insert into Cities (CityName) values ('Bordeaux');
insert into Cities (CityName) values ('Lũng Hồ');
insert into Cities (CityName) values ('Okahandja');
insert into Cities (CityName) values ('Syntul');
insert into Cities (CityName) values ('Shimabara');
insert into Cities (CityName) values ('Oughterard');
insert into Cities (CityName) values ('Mianay');
insert into Cities (CityName) values ('Baitang');
insert into Cities (CityName) values ('Piúma');
insert into Cities (CityName) values ('Kema');
insert into Cities (CityName) values ('Tim');
insert into Cities (CityName) values ('Ciparasi');
insert into Cities (CityName) values ('Panimbang');
insert into Cities (CityName) values ('Iksan');
insert into Cities (CityName) values ('Bukhovo');
insert into Cities (CityName) values ('Banjar Buahan');
insert into Cities (CityName) values ('Changtang');
insert into Cities (CityName) values ('Saint-Pierre');
insert into Cities (CityName) values ('Grojec');
insert into Cities (CityName) values ('Aiquile');
insert into Cities (CityName) values ('Tigaon');
insert into Cities (CityName) values ('Lons-le-Saunier');
insert into Cities (CityName) values ('Independencia');
insert into Cities (CityName) values ('Huyang');
insert into Cities (CityName) values ('Karangwungu Lor');
insert into Cities (CityName) values ('Talitsa');
insert into Cities (CityName) values ('Laurel');
insert into Cities (CityName) values ('Ipatinga');
insert into Cities (CityName) values ('Liugou');
insert into Cities (CityName) values ('Steinsel');
insert into Cities (CityName) values ('Fazhan');
insert into Cities (CityName) values ('Chenji');
insert into Cities (CityName) values ('Kuanfatu');
insert into Cities (CityName) values ('Masipi West');
insert into Cities (CityName) values ('Hirado');
insert into Cities (CityName) values ('Liulimiao');
insert into Cities (CityName) values ('Старо Нагоричане');
insert into Cities (CityName) values ('Risaralda');
insert into Cities (CityName) values ('Le Perreux-sur-Marne');
insert into Cities (CityName) values ('Merdeka');
insert into Cities (CityName) values ('Proletarsk');
insert into Cities (CityName) values ('Rattanawapi');
insert into Cities (CityName) values ('Leubatang');
insert into Cities (CityName) values ('Ayapel');
insert into Cities (CityName) values ('Bangekdewa');
insert into Cities (CityName) values ('Tangxia');
insert into Cities (CityName) values ('Outeiro de Polima');
insert into Cities (CityName) values ('Sorodot');
insert into Cities (CityName) values ('Čeladná');
insert into Cities (CityName) values ('Fylí');
insert into Cities (CityName) values ('Agago');
insert into Cities (CityName) values ('Bergen');
insert into Cities (CityName) values ('Tourcoing');
insert into Cities (CityName) values ('Oemofa');
insert into Cities (CityName) values ('Sidamulya Satu');
insert into Cities (CityName) values ('Parang');
insert into Cities (CityName) values ('Huaping');
insert into Cities (CityName) values ('Enköping');
insert into Cities (CityName) values ('Divnomorskoye');
insert into Cities (CityName) values ('Kosmonosy');
insert into Cities (CityName) values ('Mangaran');
insert into Cities (CityName) values ('Pul-e Sangī');
insert into Cities (CityName) values ('Koryčany');
insert into Cities (CityName) values ('Curahnongko');
insert into Cities (CityName) values ('Puntarenas');
insert into Cities (CityName) values ('Khorinsk');
insert into Cities (CityName) values ('Ketapang');
insert into Cities (CityName) values ('Replot');
insert into Cities (CityName) values ('Nam Sách');
insert into Cities (CityName) values ('Modimolle');
insert into Cities (CityName) values ('Lysogorskaya');
insert into Cities (CityName) values ('Kelungkung');
insert into Cities (CityName) values ('Letuyi');
insert into Cities (CityName) values ('Baicun');
insert into Cities (CityName) values ('Uusikaupunki');
insert into Cities (CityName) values ('Mahaba');
insert into Cities (CityName) values ('Rājbirāj');
insert into Cities (CityName) values ('Cruz das Almas');
insert into Cities (CityName) values ('Cisitu');
insert into Cities (CityName) values ('Kalamáta');
insert into Cities (CityName) values ('Annacotty');
insert into Cities (CityName) values ('Charlotte');
insert into Cities (CityName) values ('Sukth');
insert into Cities (CityName) values ('Alistráti');
insert into Cities (CityName) values ('Urbiztondo');
insert into Cities (CityName) values ('Štítina');
insert into Cities (CityName) values ('Monastyrshchina');
insert into Cities (CityName) values ('Muyi');
insert into Cities (CityName) values ('Qufu');
insert into Cities (CityName) values ('Lundazi');
insert into Cities (CityName) values ('Yanguan');
insert into Cities (CityName) values ('Słońsk');
insert into Cities (CityName) values ('Lagoa do Itaenga');
insert into Cities (CityName) values ('Aglalana');
insert into Cities (CityName) values ('Bern');
insert into Cities (CityName) values ('Lampa');
insert into Cities (CityName) values ('Gīvī');
insert into Cities (CityName) values ('Bergen op Zoom');
insert into Cities (CityName) values ('Madang');
insert into Cities (CityName) values ('Argenteuil');
insert into Cities (CityName) values ('Qingu');
insert into Cities (CityName) values ('Dąbie');
insert into Cities (CityName) values ('Nanbao');
insert into Cities (CityName) values ('Saarbrücken');
insert into Cities (CityName) values ('Oughterard');
insert into Cities (CityName) values ('Tianshan');
insert into Cities (CityName) values ('Honglan');
insert into Cities (CityName) values ('São Pedro de Trafaria');
insert into Cities (CityName) values ('Baie-Saint-Paul');
insert into Cities (CityName) values ('Ursynów');
insert into Cities (CityName) values ('Verkhn’odniprovs’k');
insert into Cities (CityName) values ('Viso');
insert into Cities (CityName) values ('Sidamulya Satu');
insert into Cities (CityName) values ('Sedayu');
insert into Cities (CityName) values ('Ekpoma');
insert into Cities (CityName) values ('Motala');
insert into Cities (CityName) values ('Mahong');
insert into Cities (CityName) values ('Zhangdun');
insert into Cities (CityName) values ('Dingqiao');
insert into Cities (CityName) values ('Dateng');
insert into Cities (CityName) values ('Wololele A');
insert into Cities (CityName) values ('Orekhovo-Zuyevo');
insert into Cities (CityName) values ('Nangka');
insert into Cities (CityName) values ('Zhaoqing');
insert into Cities (CityName) values ('Phong Điền');
insert into Cities (CityName) values ('Hövsan');
insert into Cities (CityName) values ('Washington');
insert into Cities (CityName) values ('Guxi');
insert into Cities (CityName) values ('Niandou');
insert into Cities (CityName) values ('Pontevedra');
